// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package go_graphql

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Teacher struct {
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	Qualification string `json:"qualification"`
}
